server:
  tomcat:
    accesslog:
      enabled: true
      directory: "/dev"
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:
      pattern: "[ACCESS] %{org.apache.catalina.AccessLog.RemoteAddr}r %l %t %D %F %B %S vcap_request_id:%{X-Vcap-Request-Id}i"

logging:
  level:
    com.atomist.spring.agent: DEBUG

atomist:
  enabled: true
  debug: true
  url: 'https://webhook.atomist.com/atomist/application/teams/A2MO4H2RG'
  environment:
    domain: '${ATOMIST_ENVIRONMENT:${vcap.application.space_name:development}}'
    pod: '${HOSTNAME:${random.value}}'
